### ISSUE TITLE
alors bonjour

### ISSUE THREAD

**Issue by 2klm** [Emmanuel-aidan/LaFleurSymfony#1]
j'ai regardé vos mahara...
C'est pas terrible hein
Je vous rappelle que vous avez un oral blanc avec mr forest le 18 mai sur votre veille technologique, j'espère que vous aurez des meilleurs résultats qu'au controle de P.O que je m’apprête à vous rendre

**Comment by Emmanuel-aidan** [comment]
Mdr. Carrément un mail.
